#!/usr/bin/env php
<?php
require("funcs.php");
$config_file_path = "php/config.ini";

if(!file_exists($config_file_path))
  copy_or_die($config_file_path.'.dist', $config_file_path);

$config = parse_ini_file($config_file_path, true) or die("Error loading config file. Aborting.\n\n");

if(console_has_option("-a"))
  $do_apache_config = true;

echoln("Starting script!!");

if(!config_get_option("project_name"))
  $project_name = read_from_keyboard("\nProject name: ");

$base_path = '..';

if(file_exists("$base_path/$project_name"))
  die("Directory '$base_path/$project_name' already exists. Aborting.\n\n");

mkdir_or_die("$base_path/$project_name");
$project_dir = realpath("$base_path/$project_name");
chdir($project_dir) or die("Can't change to new dir: '".realpath("$base_path/$project_name")."'. Aborting.\n\n");

# init sf project as git project
system_call("git init");

echoln("Adding libraries");
mkdir_or_die("lib/vendor");

system_call("git submodule add ".$config['urls']['symfony']." lib/vendor/symfony");

echoln("** creating project $project_name...");

system_call("php lib/vendor/symfony/data/bin/symfony generate:project --orm=propel $project_name");
system_call("php symfony generate:app frontend --csrf-secret=whisky_tango_foxtrot");
touch("cache/.gitkeep") or die("Can't create file: 'cache/.gitkeep' for some reason. Aborting.\n\n");
touch("log/.gitkeep") or die("Can't create file: 'log/.gitkeep' for some reason. Aborting.\n\n");

# add latest Propel 1.x plugin as submodule
echoln("Adding Propel");
system_call("git submodule add ".$config['urls']['sfPropelORMPlugin']." plugins/sfPropelORMPlugin");

# set HTTPS as default protocol to avoid firewall issues
system_call("git config --global url.\"https://\".insteadOf git://");

# add mpProjectPlugin
echoln("Adding mpProjectPlugin");
system_call("git submodule add ".$config['urls']['mpProjectPlugin']." plugins/mpProjectPlugin");

echoln("Updating all submodules...");
system_call("git submodule update --init --recursive");

echoln("More filesystem tweaks from mpProjectPlugin...");
copy_or_die("plugins/mpProjectPlugin/config/gitignore_example.dist", ".gitignore");
copy_or_die("plugins/mpProjectPlugin/config/databases.yml.dist", "config/databases.yml.dist");
copy_or_die("config/databases.yml.dist", "config/databases.yml");
copy_or_die("plugins/mpProjectPlugin/config/schema.custom.yml", "config/schema.custom.yml");
copy_or_die("plugins/mpProjectPlugin/apps/foo/config/settings.yml", "apps/frontend/config/settings.yml");
copy_or_die("plugins/mpProjectPlugin/apps/foo/config/factories.yml", "apps/frontend/config/factories.yml");
mkdir_or_die('config/error', null, true);
copyr("plugins/mpProjectPlugin/config/error", "config/error");
copyr("plugins/mpProjectPlugin/apps/foo/i18n", "apps/frontend/");
copyr("plugins/mpProjectPlugin/apps/foo/templates/", "apps/frontend/templates/");
copy_or_die("plugins/mpProjectPlugin/config/unavailable.php", "config/unavailable.php");
copy_or_die("plugins/mpProjectPlugin/lib/form/BaseFormPropel.class.php", "lib/form/BaseFormPropel.class.php");
mkdir_or_die("lib/filter");
copy_or_die("plugins/mpProjectPlugin/lib/filter/BaseFormFilterPropel.class.php", "lib/filter/BaseFormFilterPropel.class.php");

# add useful scripts to bin/ directory
mkdir_or_die('bin');
copyr("plugins/mpProjectPlugin/bin/", "bin/");

replace_in_file("PROJECT_NAME", $project_name, "apps/frontend/config/factories.yml");
replace_in_file("sfFormSymfony", "mpForm", "lib/form/BaseForm.class.php");
replace_in_file("sfPropelPlugin", "sfPropelORMPlugin", "config/propel.ini");
replace_in_file("propel.addTimeStamp        = true", "propel.addTimeStamp        = false", "config/propel.ini");
replace_in_file("'sfPropelPlugin'", "'sfPropelORMPlugin', 'mpProjectPlugin'", "config/ProjectConfiguration.class.php");

# project url: localhost/project_name => need to fix this file
replace_in_file("#RewriteBase /", "RewriteBase /$project_name", "web/.htaccess");

# ProjectConfiguration.class.php is ready, time to publish assets
echoln("Publishing plugin assets...");
system_call("php symfony plugin:publish-assets");

# apache config
copy_or_die("plugins/mpProjectPlugin/config/apache_example.conf.dist", "plugins/mpProjectPlugin/config/apache_example.conf");
replace_in_file("PROJECT_NAME", $project_name, "plugins/mpProjectPlugin/config/apache_example.conf");
replace_in_file("PROJECT_DIR", $project_dir, "plugins/mpProjectPlugin/config/apache_example.conf");

# publish this project in apache

if(isset($do_apache_config))
{
  echoln("In order to publish your project in Apache, I may ask you for sudo password...");
  system_call("sudo ln -s $project_dir/plugins/mpProjectPlugin/config/apache_example.conf /etc/apache2/conf.d/$project_name");
  system_call("sudo service apache2 graceful");
}

# Update git repo and clear cache

system_call("git add .");
system_call("git commit -m \"Very first commit of this project\"");
system_call("php symfony cc");

echoln("All tasks completed!");

if(isset($do_apache_config))
{
  echoln("You can now test your project at http://localhost/$project_name/frontend_dev.php right away!");
}