#!/bin/bash

# abort on any error
set -e

. bash/colors.txt

if [ ! -f bash/config.txt ];
then
    cp bash/config.txt.dist bash/config.txt
fi

. bash/config.txt

function title {
  cecho ${ansi_yellow} "============================================================"
  cecho ${ansi_yellow} $1
  cecho ${ansi_yellow} "============================================================"
}

while getopts "ha" opt; do
  case $opt in
    h)
      show_help=1
      ;;
    a)
      apache_deploy=1
      ;;
  esac
done

if [ -n "$show_help" ]
then
  cat <<EOF
  
  Usage: bash/generate [-h] | [-a]

  -h  show this help screen
  -a  perform an apache deployment of your app, doing a symlink on /etc/apache2/conf.d

EOF
  exit
fi

# starting...
clear

title "Starting script!!"

if [ -z "$project_name" ]
then
  echo -n "Project name: "
  read project_name
fi

base_path=${base_path:-~}

mkdir ${base_path}/${project_name}
cd ${base_path}/${project_name}
project_dir_unescaped=`pwd`
project_dir=${project_dir_unescaped//'/'/"\/"}

# init sf project as git project
git init

title "Adding libraries"
mkdir -p lib/vendor

cecho $ansi_blue "* symfony 1.4: "
git submodule add $symfony_url lib/vendor/symfony

cecho $ansi_blue "** creating project $project_name..."

php lib/vendor/symfony/data/bin/symfony generate:project --orm=propel $project_name
./symfony generate:app frontend --csrf-secret=whisky_tango_foxtrot
touch cache/.gitkeep
touch log/.gitkeep

# add latest Propel 1.x plugin as submodule
cecho $ansi_blue "Adding Propel"
git submodule add $sfPropelORMPlugin_url plugins/sfPropelORMPlugin

# set HTTPS as default protocol to avoid firewall issues
git config --global url."https://".insteadOf git://

# add mpProjectPlugin
cecho $ansi_blue "Adding mpProjectPlugin"
git submodule add ${mpProjectPlugin_url} plugins/mpProjectPlugin

cecho $ansi_blue "Updating all submodules..."
git submodule update --init --recursive

cecho $ansi_blue "More filesystem tweaks from mpProjectPlugin..."
cp plugins/mpProjectPlugin/config/gitignore_example.dist .gitignore
cp plugins/mpProjectPlugin/config/databases.yml.dist config/databases.yml.dist
cp config/databases.yml.dist config/databases.yml
cp plugins/mpProjectPlugin/config/schema.custom.yml config/schema.custom.yml
cp plugins/mpProjectPlugin/apps/foo/config/settings.yml apps/frontend/config/settings.yml
cp plugins/mpProjectPlugin/apps/foo/config/factories.yml apps/frontend/config/factories.yml
cp -r plugins/mpProjectPlugin/config/error config/
cp -r plugins/mpProjectPlugin/apps/foo/i18n apps/frontend/
cp plugins/mpProjectPlugin/apps/foo/templates/* apps/frontend/templates/
cp plugins/mpProjectPlugin/config/unavailable.php config/unavailable.php
cp plugins/mpProjectPlugin/lib/form/BaseFormPropel.class.php lib/form/
mkdir -p lib/filter
cp plugins/mpProjectPlugin/lib/filter/BaseFormFilterPropel.class.php lib/filter/

# add useful scripts to bin/ directory
cp -r plugins/mpProjectPlugin/bin .

sed -i "s/PROJECT_NAME/$project_name/g" apps/frontend/config/factories.yml
sed -i "s/sfFormSymfony/mpForm/g" lib/form/BaseForm.class.php
sed -i "s/sfPropelPlugin/sfPropelORMPlugin/g" config/propel.ini
sed -i "s/propel.addTimeStamp        = true/propel.addTimeStamp        = false/g" config/propel.ini
sed -i "s/'sfPropelPlugin'/'sfPropelORMPlugin', 'mpProjectPlugin'/g" config/ProjectConfiguration.class.php

# project url: localhost/project_name => need to fix this file
sed -i "s/#RewriteBase \//RewriteBase \/$project_name/g" web/.htaccess

# ProjectConfiguration.class.php is ready, time to publish assets
cecho $ansi_blue "Publishing plugin assets..."
./symfony plugin:publish-assets

# apache config
cp plugins/mpProjectPlugin/config/apache_example.conf.dist plugins/mpProjectPlugin/config/apache_example.conf
sed -i "s/PROJECT_NAME/$project_name/g" plugins/mpProjectPlugin/config/apache_example.conf
sed -i "s/PROJECT_DIR/$project_dir/g" plugins/mpProjectPlugin/config/apache_example.conf

# publish this project in apache

if [ -n "$apache_deploy" ]
then
  echo -e "\E[31m"
  cecho $ansi_blue "In order to publish your project in Apache, I may ask you for sudo password..."
  
  sudo ln -s ${project_dir_unescaped}/plugins/mpProjectPlugin/config/apache_example.conf /etc/apache2/conf.d/${project_name}
  sudo service apache2 graceful
fi

git add .
git commit -m "Very first commit of this project"
./symfony cc

cecho $ansi_blue "All tasks completed!"

if [ -n "$apache_deploy" ]
then
  title "You can now test your project at http://localhost/$project_name/frontend_dev.php right away!"
fi
